import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Header>
      <main className={`${inter.className} min-h-screen pt-[144.78px] px-8 pb-16 sm:px-14 md:px-24 lg:px-40`}>{children}</main>
      <Footer />
    </Header>
  )
}
